### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by AkeRyuu** [AkeRyuu/nightfall#1]
- [x] Поменять цвет на синий

- [ ] Поменять расцветку лого синюю

- [ ] Поменять все ави и пикчи на те, что в лого

- [x] Кнопки футера не работают

**Comment by Neucanoo** [comment]
Поменять расцветку лого синюю 
Чё? Яке саме лого?

**Comment by Neucanoo** [comment]
Поменять все ави и пикчи на те, что в лого 
Чё?
